apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: flagd
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo-flagd
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.12.0
    opentelemetry.io/name: opentelemetry-demo-flagd
  name: opentelemetry-demo-flagd
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      opentelemetry.io/name: opentelemetry-demo-flagd
  template:
    metadata:
      labels:
        app.kubernetes.io/component: flagd
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: opentelemetry-demo-flagd
        opentelemetry.io/name: opentelemetry-demo-flagd
    spec:
      containers:
      - command:
        - /flagd-build
        - start
        - --uri
        - file:./etc/flagd/demo.flagd.json
        env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: opentelemetry-demo-otelcol
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: FLAGD_METRICS_EXPORTER
          value: otel
        - name: FLAGD_OTEL_COLLECTOR_URI
          value: $(OTEL_COLLECTOR_NAME):4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
        image: ghcr.io/open-feature/flagd:v0.11.1
        imagePullPolicy: IfNotPresent
        name: flagd
        ports:
        - containerPort: 8013
          name: service
        resources:
          limits:
            memory: 50Mi
        volumeMounts:
        - mountPath: /etc/flagd
          name: config-rw
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: opentelemetry-demo-otelcol
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: FLAGD_METRICS_EXPORTER
          value: otel
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_COLLECTOR_NAME):4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
        image: ghcr.io/open-telemetry/demo:1.12.0-flagdui
        imagePullPolicy: IfNotPresent
        name: flagdui
        ports:
        - containerPort: 4000
          name: service
        resources:
          limits:
            memory: 150Mi
        volumeMounts:
        - mountPath: /app/data
          name: config-rw
      initContainers:
      - command:
        - sh
        - -c
        - cp /config-ro/demo.flagd.json /config-rw/demo.flagd.json && cat /config-rw/demo.flagd.json
        image: busybox
        name: init-config
        volumeMounts:
        - mountPath: /config-ro
          name: config-ro
        - mountPath: /config-rw
          name: config-rw
      serviceAccountName: opentelemetry-demo
      volumes:
      - emptyDir: {}
        name: config-rw
      - configMap:
          name: opentelemetry-demo-flagd-config
        name: config-ro
