apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.12.0
    opentelemetry.io/name: opentelemetry-demo
  name: opentelemetry-demo
