apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: otel-demo
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m
    route:
      group_by: ['alertname']
      receiver: 'sns-notifications'
    receivers:
    - name: 'sns-notifications'
      sns_configs:
      - api_url: 'https://sns.us-east-1.amazonaws.com' # AWS SNS API endpoint
        topic_arn: 'arn:aws:sns:us-east-1:865549754001:PodRestartAlertTopic' # SNS Topic ARN
        sigv4:
          region: 'us-east-1' # AWS region
        send_resolved: true
        message: |
          {
            "default": "{{ .Annotations.summary }}",
            "email": "Alert: {{ .Annotations.summary }}. Pod {{ .Labels.pod }} has restarted more than 2 times."
          }
    inhibit_rules:
    - source_match:
        alertname: Watchdog
      target_match:
        alertname: DeadMansSnitch
      equal: ['alertname']
