apiVersion: v1
kind: ConfigMap
metadata:
  name: opentelemetry-demo-prometheus-server
  namespace: otel-demo
data:
  alerting_rules.yml: |
    groups:
    - name: pod-restart-alerts
      rules:
      - alert: PodRestartCountExceeded
        expr: kube_pod_container_status_restarts_total{namespace="otel-demo"} > 2
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 2 times."
          description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} has restarted more than 2 times in 5 minutes."
  prometheus.yml: |
    global:
      evaluation_interval: 30s
      scrape_interval: 5s
      scrape_timeout: 3s
    storage:
      tsdb:
        out_of_order_time_window: 30m
    rule_files:
      - /etc/config/recording_rules.yml
      - /etc/config/alerting_rules.yml
      - /etc/config/rules
      - /etc/config/alerts
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - 'alertmanager:9093'
    scrape_configs:
    - job_name: otel-collector
      honor_labels: true
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          own_namespace: true
      relabel_configs:
      - action: keep
        regex: true
        source_labels:
        - __meta_kubernetes_pod_annotation_opentelemetry_community_demo
    - job_name: kube-state-metrics
      honor_labels: true
      kubernetes_sd_configs:
      - role: pod
        namespaces:
          names:
          - kube-system
      relabel_configs:
      - action: keep
        regex: kube-state-metrics
        source_labels:
        - __meta_kubernetes_pod_container_name
  recording_rules.yml: |
    {}
  rules: |
    {}
