apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: adservice
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo-adservice
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.12.0
    opentelemetry.io/name: opentelemetry-demo-adservice
  name: opentelemetry-demo-adservice
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      opentelemetry.io/name: opentelemetry-demo-adservice
  template:
    metadata:
      labels:
        app.kubernetes.io/component: adservice
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: opentelemetry-demo-adservice
        opentelemetry.io/name: opentelemetry-demo-adservice
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: opentelemetry-demo-otelcol
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: AD_SERVICE_PORT
          value: '8080'
        - name: FLAGD_HOST
          value: opentelemetry-demo-flagd
        - name: FLAGD_PORT
          value: '8013'
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_COLLECTOR_NAME):4318
        - name: OTEL_LOGS_EXPORTER
          value: otlp
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
        image: ghcr.io/open-telemetry/demo:1.12.0-adservice
        imagePullPolicy: IfNotPresent
        name: adservice
        ports:
        - containerPort: 8080
          name: service
        resources:
          limits:
            memory: 300Mi
        volumeMounts: null
      serviceAccountName: opentelemetry-demo
      volumes: null
