apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: quoteservice
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo-quoteservice
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.12.0
    opentelemetry.io/name: opentelemetry-demo-quoteservice
  name: opentelemetry-demo-quoteservice
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      opentelemetry.io/name: opentelemetry-demo-quoteservice
  template:
    metadata:
      labels:
        app.kubernetes.io/component: quoteservice
        app.kubernetes.io/instance: opentelemetry-demo
        app.kubernetes.io/name: opentelemetry-demo-quoteservice
        opentelemetry.io/name: opentelemetry-demo-quoteservice
    spec:
      containers:
      - env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: opentelemetry-demo-otelcol
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: QUOTE_SERVICE_PORT
          value: '8080'
        - name: OTEL_PHP_AUTOLOAD_ENABLED
          value: 'true'
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_COLLECTOR_NAME):4318
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
        image: ghcr.io/open-telemetry/demo:1.12.0-quoteservice
        imagePullPolicy: IfNotPresent
        name: quoteservice
        ports:
        - containerPort: 8080
          name: service
        resources:
          limits:
            memory: 40Mi
        securityContext:
          runAsGroup: 33
          runAsNonRoot: true
          runAsUser: 33
        volumeMounts: null
      serviceAccountName: opentelemetry-demo
      volumes: null
