apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: imageprovider
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo-imageprovider
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.12.0
    opentelemetry.io/name: opentelemetry-demo-imageprovider
  name: opentelemetry-demo-imageprovider
spec:
  ports:
  - name: tcp-service
    port: 8081
    targetPort: 8081
  selector:
    opentelemetry.io/name: opentelemetry-demo-imageprovider
  type: ClusterIP
