apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: productcatalogservice
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo-productcatalogservice
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.12.0
    opentelemetry.io/name: opentelemetry-demo-productcatalogservice
  name: opentelemetry-demo-productcatalogservice
spec:
  ports:
  - name: tcp-service
    port: 8080
    targetPort: 8080
  selector:
    opentelemetry.io/name: opentelemetry-demo-productcatalogservice
  type: ClusterIP
