apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: flagd
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo-flagd
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.12.0
    opentelemetry.io/name: opentelemetry-demo-flagd
  name: opentelemetry-demo-flagd
spec:
  ports:
  - name: tcp-service
    port: 8013
    targetPort: 8013
  - name: tcp-service-0
    port: 4000
    targetPort: 4000
  selector:
    opentelemetry.io/name: opentelemetry-demo-flagd
  type: ClusterIP
