apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: grafana
    app.kubernetes.io/version: 11.3.0
  name: opentelemetry-demo-grafana
  namespace: otel-demo
spec:
  ports:
  - name: service
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: grafana
  type: ClusterIP
