apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: valkey
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo-valkey
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.12.0
    opentelemetry.io/name: opentelemetry-demo-valkey
  name: opentelemetry-demo-valkey
spec:
  ports:
  - name: valkey
    port: 6379
    targetPort: 6379
  selector:
    opentelemetry.io/name: opentelemetry-demo-valkey
  type: ClusterIP
