apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service-collector
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/version: 1.53.0
  name: opentelemetry-demo-jaeger-collector
spec:
  clusterIP: None
  ports:
  - appProtocol: http
    name: http-zipkin
    port: 9411
    targetPort: 0
  - appProtocol: grpc
    name: grpc-http
    port: 14250
    targetPort: 0
  - name: c-tchan-trft
    port: 14267
    targetPort: 0
  - appProtocol: http
    name: http-c-binary-trft
    port: 14268
    targetPort: 0
  - appProtocol: grpc
    name: otlp-grpc
    port: 4317
    targetPort: 0
  - appProtocol: http
    name: otlp-http
    port: 4318
    targetPort: 0
  selector:
    app.kubernetes.io/component: all-in-one
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: jaeger
