apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: loadgenerator
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opentelemetry-demo-loadgenerator
    app.kubernetes.io/part-of: opentelemetry-demo
    app.kubernetes.io/version: 1.12.0
    opentelemetry.io/name: opentelemetry-demo-loadgenerator
  name: opentelemetry-demo-loadgenerator
spec:
  ports:
  - name: tcp-service
    port: 8089
    targetPort: 8089
  selector:
    opentelemetry.io/name: opentelemetry-demo-loadgenerator
  type: ClusterIP
