apiVersion: v1
kind: Service
metadata:
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: 'true'
  labels:
    app.kubernetes.io/component: otel-demo-opensearch
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/version: 2.18.0
  name: otel-demo-opensearch-headless
spec:
  clusterIP: None
  ports:
  - name: http
    port: 9200
  - name: transport
    port: 9300
  - name: metrics
    port: 9600
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opensearch
