apiVersion: v1
kind: Service
metadata:
  annotations: {}
  labels:
    app.kubernetes.io/component: otel-demo-opensearch
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opensearch
    app.kubernetes.io/version: 2.18.0
  name: otel-demo-opensearch
spec:
  ports:
  - name: http
    port: 9200
    protocol: TCP
  - name: transport
    port: 9300
    protocol: TCP
  - name: metrics
    port: 9600
    protocol: TCP
  selector:
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: opensearch
  type: ClusterIP
