apiVersion: v1
data:
  alerting_rules.yml: '{}

    '
  alerts: '{}

    '
  allow-snippet-annotations: 'false'
  prometheus.yml: "global:\n  evaluation_interval: 30s\n  scrape_interval: 5s\n  scrape_timeout:\
    \ 3s\nstorage:\n  tsdb:\n    out_of_order_time_window: 30m\nrule_files:\n- /etc/config/recording_rules.yml\n\
    - /etc/config/alerting_rules.yml\n- /etc/config/rules\n- /etc/config/alerts\n\
    scrape_configs:\n- honor_labels: true\n  job_name: otel-collector\n  kubernetes_sd_configs:\n\
    \  - namespaces:\n      own_namespace: true\n    role: pod\n  relabel_configs:\n\
    \  - action: keep\n    regex: true\n    source_labels:\n    - __meta_kubernetes_pod_annotation_opentelemetry_community_demo\n"
  recording_rules.yml: '{}

    '
  rules: '{}

    '
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: opentelemetry-demo
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: prometheus
    app.kubernetes.io/version: v2.55.1
  name: opentelemetry-demo-prometheus-server
  namespace: otel-demo
